### ISSUE TITLE
Abstract from AWS

### ISSUE THREAD

**Issue by UncleFirefox** [Rydra/melange#3]
Hi Rydra,

Very nice work, after reading the code a little bit and problems that this library wants to solve. Don't you think you'd broad the adoption if you enabled other pub/sub mechanisms to play in? Obviously you got the first AWS implementation but I'd like to see Kafka or others in the mix! Future roadmap maybe? ;)

**Comment by Rydra** [comment]
Hi UncleFirefox,

I'm working on a branch, *feature/major-refactor*, that intends to abstract AWS away, since my next item in the roadmap was to add support to RabbitMQ. That way, by implementing just a couple of classes, more systems may be added to the collection of supported messaging systems. I would have to study Kafka to see if it fits the use case this library solves, which is the creation of autonomous microservices.

I appreciate your compliment on this library :). In fact my next step as well would be to port this to .NET (I would have to study whether a similar solution already exists though).

**Comment by Rydra** [comment]
@UncleFirefox Melange 3.0 is now in the air! I separated the architecture by using a custom variation of the abstract factory pattern, so now it is very easy to add new messaging brokers into play. I added documentation explaining this.

I appreciate your issue, since you motivated me to speed up the roadmap :D
